version: "3.7"

networks:
   homenet:
      external: true

services:
   nginx-manager:
      image: jc21/nginx-proxy-manager:latest
      container_name: nginx-manager
      restart: always
      ports:
         - 80:80
         - 81:81
         - 443:443
      environment:
         DB_MYSQL_PORT: 3306
         DB_MYSQL_USER: nginx
         DB_MYSQL_PASSWORD: nginxPass00
         DB_MYSQL_HOST: mysql-nginx
         DB_MYSQL_NAME: nginx
         DISABLE_IPV6: 'true'
         X_FRAME_OPTIONS: sameorigin
      volumes:
         - ./data/nginxmanager/data:/data
         - ./data/nginxmanager/letsencrypt:/etc/letsencrypt
      networks: 
         - homenet
      depends_on: 
         - mysql-nginx
         
   mysql-nginx:
      image: jc21/mariadb-aria:10.4
      container_name: mysql-nginx
      restart: always
      expose: 
         - 3306
      environment:
         MYSQL_ROOT_PASSWORD: mysqlPass00
         MYSQL_DATABASE: mysql-nginx
         MYSQL_USER: nginx
         MYSQL_PASSWORD: nginxPass00
      volumes:
         - ./data/nginxmanager/db:/var/lib/mysql
      networks: 
         - homenet

   portainer:
      container_name: portainer
      image: portainer/portainer-ce
      restart: always
      networks:
         - homenet
      volumes:
         - ./data/portainer/data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      expose: 
         - 9000
         - 8000

   reposilite:
      image: dzikoysk/reposilite
      container_name: reposilite
      restart: always
      volumes:
         - ./data/reposilite/data:/app/data
      networks:
         - homenet
      expose: 
         - 80

   jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      restart: always
      privileged: true
      expose: 
         - 8080
         - 50000
      environment:
         DOCKER_TLS_CERTDIR: ./certs
      volumes:
         - ./data/jenkins/data:/var/jenkins_home:rw
         - ./data/jenkins/certs:/certs/client
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - homenet

   gitlab:
      container_name: gitlab
      image: gitlab/gitlab-ce
      restart: always
      hostname: gitlab.fenrir-it.eu
      networks:
        - homenet
      expose: 
         - 80
         - 443
         - 22
      volumes:
         - ./data/gitlab/config:/etc/gitlab
         - ./data/gitlab/logs/:/var/log/gitlab
         - ./data/gitlab/data:/var/opt/gitlab

   redmine:
      container_name: redmine
      restart: always
      image: redmine
      environment:
         REDMINE_DB_POSTGRES: redmine-db
         REDMINE_DB_PORT: 5432
         REDMINE_DB_USERNAME: redmine
         REDMINE_DB_PASSWORD: dbRedminePass00
         REDMINE_DB_DATABASE: redmine
      expose: 
         - 3000
      volumes:
         - ./data/redmine/data:/usr/src/redmine/files
         - ./data/redmine/themes:/usr/src/redmine/public/themes
         - ./data/redmine/plugins:/usr/src/redmine/plugins
      networks: 
         - homenet
      depends_on:
         - redmine-db

   redmine-db:
      image: postgres:13.1
      container_name: redmine-db
      restart: always
      expose: 
         - 5432
      environment:
         POSTGRES_PASSWORD: dbRedminePass00
         POSTGRES_DB: redmine
         POSTGRES_USER: redmine
      networks:  
         - homenet
      volumes:
         - ./data/redmine/db:/var/lib/postgresql/data
            
   