version: "3.7"

networks:
   homenet:
      external: true

services:
   nginx-manager:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: nginx-manager
      ports:
         - '80:80'
         - '81:81'
         - '443:443'
      environment:
         - DB_MYSQL_PORT: 3306
         - DB_MYSQL_USER: "nginx"
         - DB_MYSQL_PASSWORD: "nginxPass00"
         - DB_MYSQL_HOST: "mysql-nginx"
         - DB_MYSQL_NAME: "nginx"
         - DISABLE_IPV6: 'true'
         - X_FRAME_OPTIONS: "sameorigin"
      volumes:
         - ./data/nginxmanager/data:/data
         - ./data/nginxmanager/letsencrypt:/etc/letsencrypt
      networks: 
         - homenet
      depends_on: 
         - mysql-nginx
         
   mysql-nginx:
      image: 'jc21/mariadb-aria:10.4'
      container_name: mysql-nginx
      expose: 
         - 3306
      environment:
         - MYSQL_ROOT_PASSWORD: 'mysqlPass00'
         - MYSQL_DATABASE: 'mysql-nginx'
         - MYSQL_USER: 'nginx'
         - MYSQL_PASSWORD: 'nginxPass00'
      volumes:
         - ./data/nginxmanager/db:/var/lib/mysql
      networks: 
         - homenet

   portainer:
      container_name: portainer
      image: portainer/portainer-ce
      restart: always
      networks:
         - homenet
      volumes:
         - ./data/portainer/data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      expose: 
         - 9000
         - 8000

   reposilite:
      image: dzikoysk/reposilite
      container_name: reposilite
      restart: always
      volumes:
         - ./data/reposilite/data:/app/data
      networks:
         - homenet
      expose: 
         - 80

   jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      restart: always
      privileged: true
      expose: 
         - 8080
         - 50000
      environment:
         - DOCKER_TLS_CERTDIR=./certs
      volumes:
         - ./data/jenkins/data:/var/jenkins_home
         - ./data/jenkins/certs:/certs/client
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - homenet

   gitlab:
      container_name: gitlab
      image: gitlab/gitlab-ce
      restart: always
      hostname: 'gitlab.fenrir-it.eu'
      networks:
        - homenet
      expose: 
         - 80
         - 443
         - 22
      volumes:
         - ./data/gitlab/config:/etc/gitlab
         - ./data/gitlab/logs/:/var/log/gitlab
         - ./data/gitlab/data:/var/opt/gitlab

   openproject:
      image: openproject/community:11
      container_name: openproject
      restart: always
      environment:
         - SECRET_KEY_KASE=iuxIVeGkSZN+uTFoJYD6GVttU/cxUx/I3imiovGJuO8=
      networks:
         - homenet
      volumes:
         - ./data/openproject/pgdata:/var/openproject/pgdata
         - ./data/openproject/assets:/var/openproject/assets
      expose: 
         - 80

   